// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileDialog() {
  return window['go']['main']['App']['FileDialog']();
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}
