// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DatabaseButtonClicked(arg1:string):Promise<void>;

export function FileDialog():Promise<string>;

export function Query(arg1:string):Promise<string>;
